FROM node:8.7.0

COPY . /root

# WORKDIR /root

# npm install --registry=https://registry.npm.taobao.org --production && egg-scripts start --port=7001 --daemon --env=prod --title=indexy-api --workers=4

CMD npm start
